[package]
name = "key-listener"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
device_query = "3.0.1"
enigo = "0.3.0"
serde = { version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
